[package]
name = "gaia_backend"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "gaia_backend"
path = "src/main.rs"

[[bin]]
name = "init_db"
path = "src/bin/init_db.rs"

[[bin]]
name = "migrate_data_local"
path = "src/bin/migrate_data_local.rs"

[dependencies]
tokio = { version = "1.36", features = ["full"] }
axum = "0.7"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sqlx = { version = "0.7", features = ["runtime-tokio-rustls", "postgres", "json"] }
tower-http = { version = "0.5", features = ["cors"] }
dotenvy = "0.15"
tracing = "0.1"
tracing-subscriber = "0.3"
geojson = "0.24"
postgis = "0.9.0"
futures = "0.3.31"
indicatif = "0.17.9"
chrono = "0.4.39"
idna = "=0.4.0"
url = "=2.4.1"